spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservercloud-config-hlao-dev
---
spring:
  profiles: test
  application:
    name: microservercloud-config-hlao-test